DROP TABLE IF EXISTS TKS_SUBCATEGORY;
CREATE TABLE TKS_SUBCATEGORY(ID VARCHAR(45) NOT NULL PRIMARY KEY,VERSION INTEGER,NAME VARCHAR(400));
INSERT INTO TKS_SUBCATEGORY VALUES
('0',0,'DRAGONS'),
('1',0,'TIGERS'),
('2',0,'YOUTH'),
('3',0,'CADET'),
('4',0,'JUNIOR'),
('5',0,'SENIOR'),
('6',0,'ULTRA'),
('7',0,'CADET MIN'),
('8',0,'JUNIOR MIN'),
('9',0,'SENIOR MIN'),
('10',0,'PARA K41'),
('11',0,'PARA K44');